version: "3.7"
services:
  liveterm:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '3100'
    ports:
      - '3100:3000'
    volumes:
      - ./src/:/home/node/app/src
    command: npm run dev
